services:
  postgres:
    image: postgres:16-alpine
    container_name: finly-postgres
    environment:
      POSTGRES_DB: finly_db
      POSTGRES_USER: finly_user
      POSTGRES_PASSWORD: finly_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finly-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finly_user -d finly_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: finly-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finly_db
      SPRING_DATASOURCE_USERNAME: finly_user
      SPRING_DATASOURCE_PASSWORD: finly_pass
      JWT_SECRET: ZmlubHlfc3VwZXJfc2VjcmV0X2tleV9jaGFuZ2VfaW5fcHJvZHVjdGlvbl8xMjM0NTY3ODk=
      JWT_EXPIRATION: 86400000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - finly-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: finly-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - finly-network

volumes:
  postgres_data:

networks:
  finly-network:
    driver: bridge
